### ISSUE TITLE
PHP8 support

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe-labs/silverstripe-behat-extension#198]
**Blocked waiting for all the phpunit9 PRs to be merged**

Get behat installable and running on a local environment running PHP8

This will require upgrading the behat/behat dependency from 3.2 to ^3.8 - https://github.com/Behat/Behat/releases/tag/v3.8.0

### ACs
- This module is PHP8 compatible
- This change has been tested through a Travis CI build to prove it works - silverstripe/admin could be a good test case

### PR
- [x] https://github.com/silverstripe/silverstripe-behat-extension/pull/207

**Comment by emteknetnz** [comment]
Running behat with php8 worked - https://github.com/emteknetnz/silverstripe-admin/runs/4134074742?check_suite_focus=true

Using this gha config on emteknetnz/silverstripe-admin
```
name: Module CI

on:
  push:
  pull_request:

jobs:
  ci:
    uses: silverstripe/github-actions-ci-cd/.github/workflows/ci.yml@0.1.10
    # this is for testing https://github.com/silverstripe/silverstripe-behat-extension/issues/198
    with:
      run_phpunit: false
      run_phplinting: false
      run_endtoend: true
      composer_require_extra: silverstripe/frameworktest:0.4.2
      extra_jobs: |
        - php: '8.0'
          endtoend: true
```
